let str1 = "Hello";
let str2 = "World";
let str3 = str1 + ", " + str2 + "!";
let str4 = str1.concat(", ", str2, "!");
console.log(str4);
console.log(str3);
console.log(typeof str3);
console.log(str3.length);
console.log(`1+2=${1 + 2}`);
console.log(str4.slice(0, 5));
console.log(str4.substring(0, 5));
